name: franklin
services:
  gibneysolr:
    type: compose
    scanner: false # TODO: temp
    services:
      user: root
      image: quay.io/upennlibraries/upenn_solr:7.7.0
#      TODO: this does not appear to be run on lando start
#      command: sh -c "/opt/solr/bin/solr start -c -f -m 2g -p 8983 -Dsolr.jetty.request.header.size=65536"
#        /opt/solr/bin/solr create_collection -c franklin-dev -d franklin && \
#        /opt/solr/bin/solr create_collection -c franklin-test -d franklin && \
      ports:
        - '8983:8983'
      environment:
        LANDO_DROP_USER: solr
proxy:
  gibneysolr:
    - franklin.solr.lndo.site:8983
